//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ID { get; set; }
        public int codeID { get; set; }
        public string title { get; set; }
        public string codeText { get; set; }
        public int price { get; set; }
    }
}
